### ISSUE TITLE
information leakage

### ISSUE THREAD

**Issue by kennys2333** [ecjia/ecjia-daojia#20]
helper.php file line 315 creates the .env file Content is：$envPath = base_path() . DIRECTORY_SEPARATOR . '.env';
Its content is to create a .env file in the root directory and write the database account, password, and database name

**Comment by royalwang** [comment]
What is the problem?

**Comment by kennys2333** [comment]
> 问题是什么？
Help during system installation The PHP file is created on line 315 Env file content and write some sensitive information of the server, resulting in the leakage of sensitive information
