### ISSUE TITLE
安装完成打开首页报错

### ISSUE THREAD

**Issue by chenyang137** [ecjia/ecjia-daojia#21]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/34909204/165723312-044650a4-077b-4a9a-9315-c23dcf73ceb8.png">
<img width="972" alt="image" src="https://user-images.githubusercontent.com/34909204/165723419-efb16886-3226-4b40-9790-4136170f1733.png">

**Comment by royalwang** [comment]
安装失败导致的，把.env文件权限设置可写，在重新安装试一试。
