### ISSUE TITLE
1.12 session 重构后未完全做兼容

### ISSUE THREAD

**Issue by minosss** [ecjia/ecjia-daojia#4]
v1.12

打开 `admin_message` 页面

你们在1.12日志说重构了后台的session, 用新的表`session`来管理

`session_model.class.php` 这个文件还是用`sessions`，重设置后

`admin_message.php` 又使用了`sessions`的字段`adminid`去获取管理员

**Comment by royalwang** [comment]
admin_message.php中查询session的功能已经废弃了，新版本中已经修复了。
